export interface TemplateDefinition {
  id: string;
  name: string;
  tag: string;
  desc: string;
  supportsPhoto: boolean;
  sectionOrder: Array<"summary" | "education" | "skills" | "projects" | "experience" | "achievements" | "certifications">;
  headerStyle: "centered" | "left" | "banner" | "side_panel" | "profile_card" | "portrait_left" | "split" | "timeline" | "dual_block" | "matrix" | "numbered";
  photoPlacement: "none" | "top_right" | "top_left" | "top_center" | "sidebar" | "inline";
  textAlignment: "left" | "center";
  spacingDensity: "compact" | "normal" | "spacious";
  atsFriendly: boolean;
  bestFor: string;
  accentColor?: string;
  isAutoGenerateCard?: boolean;
}

export const TEMPLATES_CONFIG: TemplateDefinition[] = [
  // ── GROUP A: PLAIN RESUME TEMPLATES (1 Auto-Generate + 20 Plain Templates = 21 Total) ──
  {
    id: "auto_generate_plain",
    name: "Auto Generate by ATSLift",
    tag: "✨ TRUST ATSLIFT",
    desc: "Analyses your skills, projects, and academics to select the best template.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Auto-Select Best",
    accentColor: "#1e293b",
    isAutoGenerateCard: true,
  },
  {
    id: "modern",
    name: "Classic ATS",
    tag: "Single Column ATS",
    desc: "Clean single-column layout. Top centered or left name. Maximum ATS pass rate.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Corporate Applications",
    accentColor: "#1e293b",
  },
  {
    id: "recruiter_scan",
    name: "Recruiter Scan",
    tag: "Fast 10s Scan",
    desc: "Bold left header with 1-line title. Education & Skills placed first for quick scans.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Campus Placements",
    accentColor: "#0f172a",
  },
  {
    id: "skills_first",
    name: "Skills-First Tech",
    tag: "Tool & Stack Focus",
    desc: "Categorized skills highlighted at top. Best for technical toolsets & developers.",
    supportsPhoto: false,
    sectionOrder: ["skills", "projects", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Software Engineering",
    accentColor: "#1e3a8a",
  },
  {
    id: "project_first",
    name: "Project-First Builder",
    tag: "Project Heavy",
    desc: "Projects placed immediately after summary. Outcome-focused bullets for builders.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Project Heavy Profiles",
    accentColor: "#18181b",
  },
  {
    id: "academic_premium",
    name: "Academic Premium",
    tag: "Formal Academic",
    desc: "Formal structure with Education and Research first. Minimalist divider lines.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Higher Studies & Research",
    accentColor: "#334155",
  },
  {
    id: "one_page_dense",
    name: "One-Page Dense",
    tag: "High Density",
    desc: "Tight spacing and compact typography. Fits maximum value into one page cleanly.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "Dense Profiles",
    accentColor: "#0f172a",
  },
  {
    id: "modern_minimal",
    name: "Modern Minimal",
    tag: "Generous Whitespace",
    desc: "Large name top left, clean thin lines, generous whitespace. Modern aesthetic.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Product & UI Engineering",
    accentColor: "#1e293b",
  },
  {
    id: "impact_focused",
    name: "Impact-Focused",
    tag: "Outcome Headlines",
    desc: "Strong role headline under name with quantified action bullet points.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Product & Management",
    accentColor: "#1e3a8a",
  },
  {
    id: "developer_portfolio",
    name: "Developer Portfolio",
    tag: "GitHub & Demos",
    desc: "Main emphasis on projects with GitHub repository and live demo links prominent.",
    supportsPhoto: false,
    sectionOrder: ["projects", "skills", "experience", "education", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Full-Stack & Web Dev",
    accentColor: "#0f172a",
  },
  {
    id: "global_professional",
    name: "Global Professional",
    tag: "Corporate Standard",
    desc: "Formal corporate layout. Structured, balanced, and conservative for MNC hiring.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "MNCs & Enterprise Tech",
    accentColor: "#18181b",
  },
  {
    id: "timeline_prof",
    name: "Timeline Professional",
    tag: "Vertical Timeline",
    desc: "Vertical timeline markers connecting experience & project milestones cleanly.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "achievements", "certifications"],
    headerStyle: "timeline",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Experienced Candidates",
    accentColor: "#1e293b",
  },
  {
    id: "dual_section",
    name: "Dual Section Resume",
    tag: "50/50 Balanced Columns",
    desc: "Equal vertical block layout dividing skills/education on left and experience on right.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "achievements"],
    headerStyle: "dual_block",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Software Engineers",
    accentColor: "#0f172a",
  },
  {
    id: "tech_spec",
    name: "Technical Specification",
    tag: "Apple Spec Matrix",
    desc: "Structured tech stack matrix tables inspired by Apple technical documentation.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "experience", "education"],
    headerStyle: "matrix",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "Backend & Cloud Roles",
    accentColor: "#1e3a8a",
  },
  {
    id: "executive_corp",
    name: "Executive Corporate",
    tag: "McKinsey Corporate",
    desc: "Luxury spacing and corporate typography inspired by McKinsey & Goldman Sachs CVs.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "education", "skills", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Corporate Leadership",
    accentColor: "#18181b",
  },
  {
    id: "research_paper",
    name: "Research Paper Resume",
    tag: "IEEE Numbered Format",
    desc: "Clean numbered academic section architecture inspired by IEEE research papers.",
    supportsPhoto: false,
    sectionOrder: ["education", "projects", "skills", "experience", "achievements", "certifications"],
    headerStyle: "numbered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Higher Studies & PhD",
    accentColor: "#334155",
  },
  {
    id: "enterprise_eng",
    name: "Enterprise Engineer",
    tag: "Problem-Solution-Result",
    desc: "Case-study project architecture highlighting Problem, Solution, and Quantified Results.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "experience", "education"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "Enterprise Engineers",
    accentColor: "#0f172a",
  },
  {
    id: "product_engineer",
    name: "Product Engineer",
    tag: "Product Portfolio",
    desc: "Product case studies breaking projects into Problem, Users, Tech Stack, and Metrics.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "education", "skills", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Startup Product Teams",
    accentColor: "#1e3a8a",
  },
  {
    id: "technical_matrix",
    name: "Technical Matrix",
    tag: "Skill Proficiency Matrix",
    desc: "Organized technical proficiency matrix displaying programming language mastery levels.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "education", "achievements"],
    headerStyle: "matrix",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Tech Specialists",
    accentColor: "#1e293b",
  },
  {
    id: "minimal_grid",
    name: "Minimal Grid",
    tag: "Apple Grid Alignment",
    desc: "Invisible grid system alignment inspired by Apple Human Interface Guidelines.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Design Tech & Engineering",
    accentColor: "#0f172a",
  },
  {
    id: "silicon_valley",
    name: "Silicon Valley",
    tag: "YC Founder Minimal",
    desc: "Ultra-concise YC founder layout. Heavy whitespace, projects first, zero fluff.",
    supportsPhoto: false,
    sectionOrder: ["projects", "experience", "skills", "education", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "YC Founders & Startups",
    accentColor: "#18181b",
  },

  // ── GROUP B: PHOTO-BASED RESUME TEMPLATES (1 Auto-Generate + 20 Photo Templates = 21 Total) ──
  {
    id: "auto_generate_photo",
    name: "Auto Generate by ATSLift",
    tag: "✨ TRUST ATSLIFT",
    desc: "Analyses your skills, projects, and academics to select the best template.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Auto-Select Photo",
    accentColor: "#1e3a8a",
    isAutoGenerateCard: true,
  },
  {
    id: "photo_executive",
    name: "Executive Photo",
    tag: "Top Corner Photo",
    desc: "Professional photo in top corner with large name banner across header.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Executive & Management",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_side_panel",
    name: "Side Photo Panel",
    tag: "Side Column",
    desc: "Narrow side column with photo, contact, and skills. Premium magazine structure.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "education", "achievements"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Creative & Tech",
    accentColor: "#0f172a",
  },
  {
    id: "photo_student_card",
    name: "Student Profile Card",
    tag: "Center Avatar",
    desc: "Centered profile photo badge at top. Friendly profile feel for freshers.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "achievements", "certifications", "experience"],
    headerStyle: "profile_card",
    photoPlacement: "top_center",
    textAlignment: "center",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Campus Applications",
    accentColor: "#1e293b",
  },
  {
    id: "photo_corporate",
    name: "Corporate Portrait",
    tag: "Left Portrait",
    desc: "Formal portrait photo top left with name and title next to it. Polished finish.",
    supportsPhoto: true,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications"],
    headerStyle: "portrait_left",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Corporate Consultancy",
    accentColor: "#334155",
  },
  {
    id: "photo_creative_tech",
    name: "Creative Tech Photo",
    tag: "Circular Accent",
    desc: "Small circular photo with modern colored accent strip. Distinct visual identity.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Startups & Product",
    accentColor: "#0f172a",
  },
  {
    id: "photo_academic",
    name: "Academic Photo",
    tag: "Restrained Photo",
    desc: "Simple headshot on top right. Education first, formal academic design.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: false,
    bestFor: "Research Submissions",
    accentColor: "#475569",
  },
  {
    id: "photo_split_hero",
    name: "Split Hero",
    tag: "Two-Block Hero",
    desc: "Split header block: Left photo & name, Right summary & contact.",
    supportsPhoto: true,
    sectionOrder: ["projects", "skills", "education", "experience", "certifications"],
    headerStyle: "split",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Portfolios & Tech",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_clean_vertical",
    name: "Clean Vertical Photo",
    tag: "1-Row Full Header",
    desc: "Single horizontal header row containing name, title, contact, and headshot.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "inline",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: false,
    bestFor: "One-Page Photo",
    accentColor: "#1e293b",
  },
  {
    id: "photo_personal_brand",
    name: "Personal Brand",
    tag: "Tagline Banner",
    desc: "Photo, name, tagline & profile block at top. Great for personal branding.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "profile_card",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Founders & Branding",
    accentColor: "#0f172a",
  },
  {
    id: "photo_premium_identity",
    name: "Premium Identity",
    tag: "Refined Badge",
    desc: "Refined photo badge with bold high-contrast typography. Sleek finish.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "experience", "projects", "education", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Executive Leadership",
    accentColor: "#18181b",
  },
  {
    id: "photo_executive_board",
    name: "Executive Board",
    tag: "Square Executive Photo",
    desc: "Top left square portrait with executive role summary and luxury business layout.",
    supportsPhoto: true,
    sectionOrder: ["summary", "experience", "projects", "education", "skills"],
    headerStyle: "portrait_left",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "MBA & Executive Board",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_magazine_cover",
    name: "Magazine Cover",
    tag: "Editorial Magazine",
    desc: "Large editorial portrait on left with text flowing gracefully around image. Inspired by Novorésumé.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "education", "skills"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Creative & Media",
    accentColor: "#0f172a",
  },
  {
    id: "photo_designer_portfolio",
    name: "Designer Portfolio",
    tag: "Behance Design Sidebar",
    desc: "Large vertical sidebar with photo, bio, skills, and main portfolio canvas. Inspired by Behance.",
    supportsPhoto: true,
    sectionOrder: ["projects", "experience", "education", "skills", "achievements"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Designers & Creative Tech",
    accentColor: "#1e293b",
  },
  {
    id: "photo_identity_card",
    name: "Identity Card Resume",
    tag: "Executive Profile Card",
    desc: "Top banner with photo inside rounded card badge beside candidate title & contact.",
    supportsPhoto: true,
    sectionOrder: ["projects", "experience", "skills", "education"],
    headerStyle: "banner",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: false,
    bestFor: "Executive Profiles",
    accentColor: "#334155",
  },
  {
    id: "photo_startup_founder",
    name: "Startup Founder",
    tag: "YC Founder Photo",
    desc: "Modern YC founder header with photo, startup tagline, product case studies & metrics.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "achievements", "education", "skills"],
    headerStyle: "banner",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Startup Founders",
    accentColor: "#18181b",
  },
  {
    id: "photo_newspaper_editorial",
    name: "Newspaper Editorial",
    tag: "Newspaper Editorial",
    desc: "Newspaper editorial layout with photo top right, 2-column flow, and elegant serif typography.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "education", "achievements"],
    headerStyle: "left",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Editorial & Leadership",
    accentColor: "#0f172a",
  },
  {
    id: "photo_profile_dashboard",
    name: "Profile Dashboard",
    tag: "Dashboard UI Layout",
    desc: "Modern dashboard layout featuring left sidebar photo, QR badge, stats, and project panel.",
    supportsPhoto: true,
    sectionOrder: ["projects", "experience", "education", "achievements", "skills"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: false,
    bestFor: "UI/UX & Tech Leads",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_european_cv",
    name: "European CV Style",
    tag: "Europass Standard",
    desc: "Formal European CV architecture with passport photo top right, nationality, and language levels.",
    supportsPhoto: true,
    sectionOrder: ["summary", "experience", "education", "projects", "skills"],
    headerStyle: "left",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "European & Global Hiring",
    accentColor: "#334155",
  },
  {
    id: "photo_premium_notion",
    name: "Premium Identity Layout",
    tag: "Notion & Apple UI",
    desc: "Circular portrait, luxury card blocks, centered title, and Notion-inspired minimalist cards.",
    supportsPhoto: true,
    sectionOrder: ["projects", "experience", "skills", "education", "achievements"],
    headerStyle: "profile_card",
    photoPlacement: "top_center",
    textAlignment: "center",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Premium Identity",
    accentColor: "#18181b",
  },
  {
    id: "photo_consulting_profile",
    name: "Consulting Profile",
    tag: "Big-4 Corporate CV",
    desc: "Corporate consulting layout with headshot, executive summary, and key competency blocks.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "experience", "projects", "education", "certifications"],
    headerStyle: "portrait_left",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Deloitte / EY / PwC Style",
    accentColor: "#1e3a8a",
  },
];

export function getTemplateById(id: string): TemplateDefinition {
  if (id === "auto_generate_plain") {
    return TEMPLATES_CONFIG.find((t) => t.id === "modern") || TEMPLATES_CONFIG[1];
  }
  if (id === "auto_generate_photo") {
    return TEMPLATES_CONFIG.find((t) => t.id === "photo_executive") || TEMPLATES_CONFIG[22];
  }
  return TEMPLATES_CONFIG.find((t) => t.id === id) || TEMPLATES_CONFIG[1];
}
