export interface TemplateDefinition {
  id: string;
  name: string;
  tag: string;
  desc: string;
  supportsPhoto: boolean;
  sectionOrder: Array<"summary" | "education" | "skills" | "projects" | "experience" | "achievements" | "certifications">;
  headerStyle: "centered" | "left" | "banner" | "side_panel" | "profile_card" | "portrait_left" | "split";
  photoPlacement: "none" | "top_right" | "top_left" | "top_center" | "sidebar" | "inline";
  textAlignment: "left" | "center";
  spacingDensity: "compact" | "normal" | "spacious";
  atsFriendly: boolean;
  bestFor: string;
  accentColor?: string;
  isAutoGenerateCard?: boolean;
}

export const TEMPLATES_CONFIG: TemplateDefinition[] = [
  // ── GROUP A: PLAIN RESUME TEMPLATES (1 Auto-Generate + 10 Plain Templates) ──
  {
    id: "auto_generate_plain",
    name: "Auto Generate by ATSLift",
    tag: "✨ TRUST ATSLIFT",
    desc: "Analyses your skills, projects, and academics to select the best template.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Auto-Select Best",
    accentColor: "#1e293b",
    isAutoGenerateCard: true,
  },
  {
    id: "modern",
    name: "Classic ATS",
    tag: "Single Column ATS",
    desc: "Clean single-column layout. Top centered or left name. Maximum ATS pass rate.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Corporate Applications",
    accentColor: "#1e293b",
  },
  {
    id: "recruiter_scan",
    name: "Recruiter Scan",
    tag: "Fast 10s Scan",
    desc: "Bold left header with 1-line title. Education & Skills placed first for quick scans.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Campus Placements",
    accentColor: "#0f172a",
  },
  {
    id: "skills_first",
    name: "Skills-First Tech",
    tag: "Tool & Stack Focus",
    desc: "Categorized skills highlighted at top. Best for technical toolsets & developers.",
    supportsPhoto: false,
    sectionOrder: ["skills", "projects", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Software Engineering",
    accentColor: "#1e3a8a",
  },
  {
    id: "project_first",
    name: "Project-First Builder",
    tag: "Project Heavy",
    desc: "Projects placed immediately after summary. Outcome-focused bullets for builders.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Project Heavy Profiles",
    accentColor: "#18181b",
  },
  {
    id: "academic_premium",
    name: "Academic Premium",
    tag: "Formal Academic",
    desc: "Formal structure with Education and Research first. Minimalist divider lines.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Higher Studies & Research",
    accentColor: "#334155",
  },
  {
    id: "one_page_dense",
    name: "One-Page Dense",
    tag: "High Density",
    desc: "Tight spacing and compact typography. Fits maximum value into one page cleanly.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "Dense Profiles",
    accentColor: "#0f172a",
  },
  {
    id: "modern_minimal",
    name: "Modern Minimal",
    tag: "Generous Whitespace",
    desc: "Large name top left, clean thin lines, generous whitespace. Modern aesthetic.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Product & UI Engineering",
    accentColor: "#1e293b",
  },
  {
    id: "impact_focused",
    name: "Impact-Focused",
    tag: "Outcome Headlines",
    desc: "Strong role headline under name with quantified action bullet points.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Product & Management",
    accentColor: "#1e3a8a",
  },
  {
    id: "developer_portfolio",
    name: "Developer Portfolio",
    tag: "GitHub & Demos",
    desc: "Main emphasis on projects with GitHub repository and live demo links prominent.",
    supportsPhoto: false,
    sectionOrder: ["projects", "skills", "experience", "education", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Full-Stack & Web Dev",
    accentColor: "#0f172a",
  },
  {
    id: "global_professional",
    name: "Global Professional",
    tag: "Corporate Standard",
    desc: "Formal corporate layout. Structured, balanced, and conservative for MNC hiring.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "MNCs & Enterprise Tech",
    accentColor: "#18181b",
  },

  // ── GROUP B: PHOTO-BASED RESUME TEMPLATES (1 Auto-Generate + 10 Photo Templates) ──
  {
    id: "auto_generate_photo",
    name: "Auto Generate by ATSLift",
    tag: "✨ TRUST ATSLIFT",
    desc: "Analyses your skills, projects, and academics to select the best template.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Auto-Select Photo",
    accentColor: "#1e3a8a",
    isAutoGenerateCard: true,
  },
  {
    id: "photo_executive",
    name: "Executive Photo",
    tag: "Top Corner Photo",
    desc: "Professional photo in top corner with large name banner across header.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Executive & Management",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_side_panel",
    name: "Side Photo Panel",
    tag: "Side Column",
    desc: "Narrow side column with photo, contact, and skills. Premium magazine structure.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "education", "achievements"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Creative & Tech",
    accentColor: "#0f172a",
  },
  {
    id: "photo_student_card",
    name: "Student Profile Card",
    tag: "Center Avatar",
    desc: "Centered profile photo badge at top. Friendly profile feel for freshers.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "achievements", "certifications", "experience"],
    headerStyle: "profile_card",
    photoPlacement: "top_center",
    textAlignment: "center",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Campus Applications",
    accentColor: "#1e293b",
  },
  {
    id: "photo_corporate",
    name: "Corporate Portrait",
    tag: "Left Portrait",
    desc: "Formal portrait photo top left with name and title next to it. Polished finish.",
    supportsPhoto: true,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications"],
    headerStyle: "portrait_left",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Corporate Consultancy",
    accentColor: "#334155",
  },
  {
    id: "photo_creative_tech",
    name: "Creative Tech Photo",
    tag: "Circular Accent",
    desc: "Small circular photo with modern colored accent strip. Distinct visual identity.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Startups & Product",
    accentColor: "#0f172a",
  },
  {
    id: "photo_academic",
    name: "Academic Photo",
    tag: "Restrained Photo",
    desc: "Simple headshot on top right. Education first, formal academic design.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: false,
    bestFor: "Research Submissions",
    accentColor: "#475569",
  },
  {
    id: "photo_split_hero",
    name: "Split Hero",
    tag: "Two-Block Hero",
    desc: "Split header block: Left photo & name, Right summary & contact.",
    supportsPhoto: true,
    sectionOrder: ["projects", "skills", "education", "experience", "certifications"],
    headerStyle: "split",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Portfolios & Tech",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_clean_vertical",
    name: "Clean Vertical Photo",
    tag: "1-Row Full Header",
    desc: "Single horizontal header row containing name, title, contact, and headshot.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "inline",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: false,
    bestFor: "One-Page Photo",
    accentColor: "#1e293b",
  },
  {
    id: "photo_personal_brand",
    name: "Personal Brand",
    tag: "Tagline Banner",
    desc: "Photo, name, tagline & profile block at top. Great for personal branding.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "profile_card",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Founders & Branding",
    accentColor: "#0f172a",
  },
  {
    id: "photo_premium_identity",
    name: "Premium Identity",
    tag: "Refined Badge",
    desc: "Refined photo badge with bold high-contrast typography. Sleek finish.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "experience", "projects", "education", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Executive Leadership",
    accentColor: "#18181b",
  },
];

export function getTemplateById(id: string): TemplateDefinition {
  if (id === "auto_generate_plain") {
    return TEMPLATES_CONFIG.find((t) => t.id === "modern") || TEMPLATES_CONFIG[1];
  }
  if (id === "auto_generate_photo") {
    return TEMPLATES_CONFIG.find((t) => t.id === "photo_executive") || TEMPLATES_CONFIG[12];
  }
  return TEMPLATES_CONFIG.find((t) => t.id === id) || TEMPLATES_CONFIG[1];
}
