export interface TemplateDefinition {
  id: string;
  name: string;
  tag: string;
  desc: string;
  supportsPhoto: boolean;
  sectionOrder: Array<"summary" | "education" | "skills" | "projects" | "experience" | "achievements" | "certifications">;
  headerStyle: "centered" | "left" | "banner" | "side_panel" | "profile_card" | "portrait_left" | "split";
  photoPlacement: "none" | "top_right" | "top_left" | "top_center" | "sidebar" | "inline";
  textAlignment: "left" | "center";
  spacingDensity: "compact" | "normal" | "spacious";
  atsFriendly: boolean;
  bestFor: string;
  accentColor?: string;
}

export const TEMPLATES_CONFIG: TemplateDefinition[] = [
  // ── GROUP A: 10 PLAIN RESUME TEMPLATES ──
  {
    id: "modern",
    name: "Classic ATS",
    tag: "Single Column ATS",
    desc: "Clean single-column layout. Top centered or left name. Standard section order for maximum ATS pass rate.",
    supportsPhoto: false,
    sectionOrder: ["summary", "education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "General ATS Applications & Corporate Pipeline",
    accentColor: "#1e293b",
  },
  {
    id: "recruiter_scan",
    name: "Recruiter Scan",
    tag: "Fast 10s Scan",
    desc: "Bold left header with 1-line title. Education & Skills placed first for fast 10-second recruiter scans.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Campus Placements & Quick Scans",
    accentColor: "#0f172a",
  },
  {
    id: "skills_first",
    name: "Skills-First Tech",
    tag: "Tool & Stack Focus",
    desc: "Categorized skills highlighted at top. Best for student developers showcasing technical toolsets.",
    supportsPhoto: false,
    sectionOrder: ["skills", "projects", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Tech Roles & Software Engineering",
    accentColor: "#1e3a8a",
  },
  {
    id: "project_first",
    name: "Project-First Builder",
    tag: "Project Heavy",
    desc: "Projects placed immediately after summary. Outcome-focused bullets for student builders.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Hackathons, Open Source & Independent Builders",
    accentColor: "#18181b",
  },
  {
    id: "academic_premium",
    name: "Academic Premium",
    tag: "Formal Academic",
    desc: "Formal structure with Education and Research/Positions first. Minimalist divider lines.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Higher Studies, Research & Internships",
    accentColor: "#334155",
  },
  {
    id: "one_page_dense",
    name: "One-Page Dense",
    tag: "High Information Density",
    desc: "Tight spacing and compact typography. Fits maximum value into one page cleanly.",
    supportsPhoto: false,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: true,
    bestFor: "Experienced Freshers & Dense Profiles",
    accentColor: "#0f172a",
  },
  {
    id: "modern_minimal",
    name: "Modern Minimal",
    tag: "Generous Whitespace",
    desc: "Large name top left, clean thin lines, generous whitespace. Modern polished aesthetic.",
    supportsPhoto: false,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: true,
    bestFor: "Design Tech, Product & UI Engineering",
    accentColor: "#1e293b",
  },
  {
    id: "impact_focused",
    name: "Impact-Focused",
    tag: "Outcome Headlines",
    desc: "Strong role headline under name (e.g. CSE Student | Full Stack). Quantified action bullets.",
    supportsPhoto: false,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "centered",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Results-Driven Candidates & Product Roles",
    accentColor: "#1e3a8a",
  },
  {
    id: "developer_portfolio",
    name: "Developer Portfolio Style",
    tag: "GitHub & Demo Links",
    desc: "Main emphasis on projects with GitHub repository and live demo links prominent.",
    supportsPhoto: false,
    sectionOrder: ["projects", "skills", "experience", "education", "certifications"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "Full-Stack, Web Dev & Open Source Engineers",
    accentColor: "#0f172a",
  },
  {
    id: "global_professional",
    name: "Global Professional",
    tag: "Corporate Standard",
    desc: "Formal corporate layout. Structured, balanced, and conservative for global hiring pipelines.",
    supportsPhoto: false,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications", "achievements"],
    headerStyle: "left",
    photoPlacement: "none",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: true,
    bestFor: "MNCs, Enterprise Tech & Financial Services",
    accentColor: "#18181b",
  },

  // ── GROUP B: 10 PHOTO-BASED RESUME TEMPLATES ──
  {
    id: "photo_executive",
    name: "Executive Photo Header",
    tag: "Top Corner Photo",
    desc: "Professional photo in top corner. Large name banner across header.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "projects", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Executive, Management & Client-Facing Roles",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_side_panel",
    name: "Side Photo Panel",
    tag: "Magazine Side Column",
    desc: "Narrow side column with photo, contact, and skills. Premium magazine structure.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "experience", "education", "achievements"],
    headerStyle: "side_panel",
    photoPlacement: "sidebar",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Creative, Tech & International Applications",
    accentColor: "#0f172a",
  },
  {
    id: "photo_student_card",
    name: "Student Profile Card",
    tag: "Center Avatar Badge",
    desc: "Centered profile photo badge at top. Friendly profile feel for fresher applications.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "achievements", "certifications", "experience"],
    headerStyle: "profile_card",
    photoPlacement: "top_center",
    textAlignment: "center",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Campus Applications & Graduate Programs",
    accentColor: "#1e293b",
  },
  {
    id: "photo_corporate",
    name: "Corporate Portrait",
    tag: "Left Portrait Header",
    desc: "Formal portrait photo top left with name and title next to it. Polished & interview ready.",
    supportsPhoto: true,
    sectionOrder: ["summary", "experience", "projects", "skills", "education", "certifications"],
    headerStyle: "portrait_left",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Corporate Placements & Consultancy",
    accentColor: "#334155",
  },
  {
    id: "photo_creative_tech",
    name: "Creative Tech Photo",
    tag: "Circular Accent Photo",
    desc: "Small circular photo with modern colored accent strip. Distinct visual identity.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Startups, UI/UX & Product Engineering",
    accentColor: "#0f172a",
  },
  {
    id: "photo_academic",
    name: "Academic Photo",
    tag: "Restrained Headshot",
    desc: "Simple headshot on top right. Education first, formal restrained academic design.",
    supportsPhoto: true,
    sectionOrder: ["education", "skills", "projects", "experience", "achievements", "certifications"],
    headerStyle: "left",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "spacious",
    atsFriendly: false,
    bestFor: "University Submissions & Research Forms",
    accentColor: "#475569",
  },
  {
    id: "photo_split_hero",
    name: "Split Hero",
    tag: "Two-Block Hero Header",
    desc: "Split header block: Left photo & name, Right summary & contact.",
    supportsPhoto: true,
    sectionOrder: ["projects", "skills", "education", "experience", "certifications"],
    headerStyle: "split",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Visual Portfolios & Modern Tech Teams",
    accentColor: "#1e3a8a",
  },
  {
    id: "photo_clean_vertical",
    name: "Clean Vertical Photo",
    tag: "1-Row Full Header",
    desc: "Single horizontal header row containing name, title, contact, and headshot.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "education", "experience", "certifications"],
    headerStyle: "banner",
    photoPlacement: "inline",
    textAlignment: "left",
    spacingDensity: "compact",
    atsFriendly: false,
    bestFor: "One-Page Photo Resumes",
    accentColor: "#1e293b",
  },
  {
    id: "photo_personal_brand",
    name: "Personal Brand",
    tag: "Tagline & Bio Banner",
    desc: "Photo, name, tagline & 'About Me' profile block at top. Great for personal branding.",
    supportsPhoto: true,
    sectionOrder: ["summary", "projects", "skills", "experience", "education", "achievements"],
    headerStyle: "profile_card",
    photoPlacement: "top_left",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "Personal Portfolios & Founder/Lead Roles",
    accentColor: "#0f172a",
  },
  {
    id: "photo_premium_identity",
    name: "Premium Identity",
    tag: "Refined Badge & High Contrast",
    desc: "Refined photo badge with bold high-contrast typography. Sleek executive finish.",
    supportsPhoto: true,
    sectionOrder: ["summary", "skills", "experience", "projects", "education", "achievements"],
    headerStyle: "banner",
    photoPlacement: "top_right",
    textAlignment: "left",
    spacingDensity: "normal",
    atsFriendly: false,
    bestFor: "High-Level Executive & Leadership",
    accentColor: "#18181b",
  },
];

export function getTemplateById(id: string): TemplateDefinition {
  return TEMPLATES_CONFIG.find((t) => t.id === id) || TEMPLATES_CONFIG[0];
}
